language: go
go:
- 1.13.x
before_install:
  - sudo apt-get update
script:
  - go build -o varnish-purge main.go
deploy:
  provider: releases
  token: GITHUB_TOKEN
  file: varnish-purge
  release_notes: "Primer build"
